const fs = require('fs');
const path = require('path');

const normalizePath = (p) => path.resolve(p).replace(/\\/g, '/');

const frontendDir = path.resolve(__dirname, 'src/');
const envPathFile = path.join(frontendDir, 'envPath.js');

// Define paths and normalize
const pyTorchXmlPath = normalizePath('src/frontend/utils/pyTorchNodes.xml');
const testDirPath = normalizePath('src/__tests__');

// Prepare file content
const fileContent = `// This file is auto-generated by setupEnvPath.js
export const PYTORCH_NODE_PATH = ${JSON.stringify(pyTorchXmlPath)};
export const TEST_DIR = ${JSON.stringify(testDirPath)};
export const TEST_PY_FILE = TEST_DIR + "/demo.py"
export const TEST_MODEL_WEIGHT = TEST_DIR + "/modelAndweights.zip";
`;

// Ensure src/frontend exists
if (!fs.existsSync(frontendDir)) {
  fs.mkdirSync(frontendDir, { recursive: true });
}

// Write or overwrite envPath.js
fs.writeFileSync(envPathFile, fileContent, 'utf8');
console.log(`✅ envPath.js written to ${envPathFile}`);
