const fs = require('fs');
const path = require('path');

const normalizePath = (p) => path.resolve(p).replace(/\\/g, '/');

function generateEnvPathFile(baseDir = __dirname) {
  const basePath = normalizePath(baseDir);
  const applicationDirPath = normalizePath(path.join(baseDir, 'application'));
  const venvPythonRelativePath =
    process.platform === 'win32'
      ? '/Scripts/python.exe'
      : '/bin/python';
  const systemPythonPath = process.env.PYTHON_PATH
    ? normalizePath(process.env.PYTHON_PATH)
    : '';
  const frontendDir = path.resolve(baseDir, 'src/');
  const envPathFile = path.join(frontendDir, 'envPath.js');

  const pyTorchXmlPath = normalizePath(
    path.join(baseDir, 'src/frontend/utils/pyTorchNodes.xml'),
  );
  const testDirPath = normalizePath(path.join(baseDir, 'src/__tests__'));
  const testModelWeightPath = normalizePath(
    path.join(baseDir, 'src/__tests__/modelAndweights.zip'),
  );

  const fileContent = `// This file is auto-generated by setupEnvPath.js
export const BASE_PATH = ${JSON.stringify(basePath)};
export const APPLICATION_DIR = BASE_PATH + "/application";
export const PYTORCH_NODE_PATH = ${JSON.stringify(pyTorchXmlPath)};
export const TEST_DIR = ${JSON.stringify(testDirPath)};
export const TEST_PY_FILE = TEST_DIR + "/demo.py";
export const TEST_MODEL_WEIGHT = ${JSON.stringify(testModelWeightPath)};
export const PYTORCH_VENV_PATH = APPLICATION_DIR + "/__MF_PYTROCH__";
export const VENV_PYTHON_PATH = PYTORCH_VENV_PATH + ${JSON.stringify(venvPythonRelativePath)};
export const PYTHON_PATH = ${JSON.stringify(systemPythonPath)};
`;

  if (!fs.existsSync(frontendDir)) {
    fs.mkdirSync(frontendDir, { recursive: true });
  }

  fs.writeFileSync(envPathFile, fileContent, 'utf8');
  console.log(`✅ envPath.js written to ${envPathFile}`);
  return envPathFile;
}

module.exports = {
  generateEnvPathFile,
};

if (require.main === module) {
  generateEnvPathFile();
}
