const fs = require('fs');
const path = require('path');

const normalizePath = (p) => path.resolve(p).replace(/\\/g, '/');

const basePath = normalizePath(__dirname);
const applicationDirPath = normalizePath(path.join(__dirname, 'application'));
const venvDirPath = normalizePath(
  path.join(applicationDirPath, '__MF_PYTROCH__'),
);
const venvPythonPath = normalizePath(
  process.platform === 'win32'
    ? path.join(venvDirPath, 'Scripts', 'python.exe')
    : path.join(venvDirPath, 'bin', 'python'),
);
const systemPythonPath = process.env.PYTHON_PATH
  ? normalizePath(process.env.PYTHON_PATH)
  : '';
const frontendDir = path.resolve(__dirname, 'src/');
const envPathFile = path.join(frontendDir, 'envPath.js');

// Define paths and normalize
const pyTorchXmlPath = normalizePath('src/frontend/utils/pyTorchNodes.xml');
const testDirPath = normalizePath('src/__tests__');
const testModelWeightPath = normalizePath('src/__tests__/modelAndweights.zip');

// Prepare file content
const fileContent = `// This file is auto-generated by setupEnvPath.js
export const BASE_PATH = ${JSON.stringify(basePath)};
export const APPLICATION_DIR = ${JSON.stringify(applicationDirPath)};
export const PYTORCH_NODE_PATH = ${JSON.stringify(pyTorchXmlPath)};
export const TEST_DIR = ${JSON.stringify(testDirPath)};
export const TEST_PY_FILE = TEST_DIR + "/demo.py";
export const TEST_MODEL_WEIGHT = ${JSON.stringify(testModelWeightPath)};
export const PYTORCH_VENV_PATH = ${JSON.stringify(venvDirPath)};
export const VENV_PYTHON_PATH = ${JSON.stringify(venvPythonPath)};
export const PYTHON_PATH = ${JSON.stringify(systemPythonPath)};
`;

// Ensure src/frontend exists
if (!fs.existsSync(frontendDir)) {
  fs.mkdirSync(frontendDir, { recursive: true });
}

// Write or overwrite envPath.js
fs.writeFileSync(envPathFile, fileContent, 'utf8');
console.log(`✅ envPath.js written to ${envPathFile}`);
