import fs from 'fs';
import path from 'path';

const normalizePath = (targetPath: string) =>
  path.resolve(targetPath).replace(/\\/g, '/');

export function generateEnvPathFile(
  baseDir: string,
  pythonPath: string = process.env.PYTHON_PATH || '',
): string {
  const basePath = normalizePath(baseDir);
  const applicationDirPath = normalizePath(path.join(baseDir, 'application'));
  const venvDirPath = normalizePath(
    path.join(applicationDirPath, '__MF_PYTROCH__'),
  );
  const venvPythonPath = normalizePath(
    process.platform === 'win32'
      ? path.join(venvDirPath, 'Scripts', 'python.exe')
      : path.join(venvDirPath, 'bin', 'python'),
  );
  const normalizedPythonPath = pythonPath ? normalizePath(pythonPath) : '';
  const frontendDir = path.resolve(baseDir, 'src/');
  const envPathFile = path.join(frontendDir, 'envPath.js');

  const pyTorchXmlPath = normalizePath(
    path.join(baseDir, 'src/frontend/utils/pyTorchNodes.xml'),
  );
  const testDirPath = normalizePath(path.join(baseDir, 'src/__tests__'));
  const testModelWeightPath = normalizePath(
    path.join(baseDir, 'src/__tests__/modelAndweights.zip'),
  );

  const fileContent = `// This file is auto-generated by setupEnvPath.js
export const BASE_PATH = ${JSON.stringify(basePath)};
export const APPLICATION_DIR = ${JSON.stringify(applicationDirPath)};
export const PYTORCH_NODE_PATH = ${JSON.stringify(pyTorchXmlPath)};
export const TEST_DIR = ${JSON.stringify(testDirPath)};
export const TEST_PY_FILE = TEST_DIR + "/demo.py";
export const TEST_MODEL_WEIGHT = ${JSON.stringify(testModelWeightPath)};
export const PYTORCH_VENV_PATH = ${JSON.stringify(venvDirPath)};
export const VENV_PYTHON_PATH = ${JSON.stringify(venvPythonPath)};
export const PYTHON_PATH = ${JSON.stringify(normalizedPythonPath)};
`;

  if (!fs.existsSync(frontendDir)) {
    fs.mkdirSync(frontendDir, { recursive: true });
  }

  fs.writeFileSync(envPathFile, fileContent, 'utf8');
  return envPathFile;
}
