name: Build Electron App on All OS

on:
  push:
    branches:
      - '**'  # Triggers on all branches

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3
        
      - name: 🏗 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: 📦 Install Dependencies
        run: npm ci
        
      - name: ✨ Check Formatting
        run: npx prettier --check "src/**/*.{ts,tsx,js,jsx,json,css,scss}"

  python-setup-test:
    runs-on: macos-latest
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3
        
      - name: 🏗 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: 📦 Install Dependencies
        run: npm ci
        
      - name: 📂 Create Directory
        run: mkdir -p src/main/installed-python
        
      - name: 📦 Extract Python Setup
        run: tar -xzf src/main/python_installer/myenv.tar.gz -C src/main/installed-python
        
      - name: 🔧 Setup Environment Path
        run: node setupEnvPath.js
        
      - name: 🧪 Run Demo Test
        run: python src/__test__/demo.py

  build:
    needs: [prettier, python-setup-test]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🏗 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install Dependencies
        run: npm install
        
      - name: 🔧 Setup Environment Path
        run: node setupEnvPath.js

      - name: 🛠 Build Electron App
        run: npm run build

      - name: 📤 Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-build-${{ runner.os }}
          path: dist/
